language: r
sudo: false
script: make build
cache: packages
r_packages:
  - rmarkdown
  - tidyverse
  - patchwork
  - readxl
os:
  - linux
  - osx
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: master